//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exzamentwo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public string Status { get; set; }
        public System.DateTime DateDelivery { get; set; }
        public int PointProduct { get; set; }
        public System.DateTime Date { get; set; }
        public int Account { get; set; }
        public int Cod { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual PointProduct PointProduct1 { get; set; }
    }
}
