//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exzamentwo
{
    using System;
    using System.Collections.Generic;
    
    public partial class StructureOrder
    {
        public int OrderID { get; set; }
        public string ProductID { get; set; }
        public int Count { get; set; }
    }
}
